### ISSUE TITLE
Node 16 is deprecated

### ISSUE THREAD

**Issue by timbms** [maierj/fastlane-action#113]
A warning is reported by GitHub for maierj/fastlane-action@v3.0.0>

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: maierj/fastlane-action@v3.0.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

Can you please address it.

**Comment by octover** [comment]
It has been addressed with https://github.com/maierj/fastlane-action/pull/112 but I think there still needs to be a new release.

**Comment by maierj** [comment]
Thanks @octover, version upgrade was just released in v3.1.0.
