### ISSUE TITLE
Using --env beta flag

### ISSUE THREAD

**Issue by kceb** [maierj/fastlane-action#42]
How would I use the following `--env` flag:
https://docs.fastlane.tools/advanced/other/#environment-variables

The options arg uses `:` and invalidates the argument

**Comment by kceb** [comment]
In the meantime I will be using a hack: https://github.com/kceb/fastlane-action/commit/42ffef1a7bc63137ee4202bc3af1bc0f86272f33

I may be missing something in the fastlane docs that allow flags to be used in the `env:beta` syntax.

If I'm not, then the better longer term solution is to also support adding and arbitrary number of flags in a similar fashion to the way options are currently handled.

**Comment by maierj** [comment]
Currently, there is no option to pass environment variables to fastlane using a file. You can only pass environment variables to the workflow step as for every other step: https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables.

I'll keep this issue open as a feature request that may be implemented in the future.

**Comment by fahrenkrug** [comment]
Hi 👋  I needed this enhancement too yesterday, so I forked this project and implemented this and it's working fine for me.

I created a PR for this: https://github.com/maierj/fastlane-action/pull/81

**Comment by maierj** [comment]
@fahrenkrug Thanks for the contribution. Feature was just released in version 2.2.0.
