### ISSUE TITLE
Using runs-on: self-hosted and I am getting errors saying it needs to sudo

### ISSUE THREAD

**Issue by pinkfish** [maierj/fastlane-action#45]
I don't see an easy way to resolve this or pass in something so it uses a local directory?

Moving to subdirectory ux/ios
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....................................
Using CFPropertyList 3.0.2
Following files may not be writable, so sudo is needed:
  /Library/Ruby/Gems/2.6.0
Using public_suffix 2.0.5
  /Library/Ruby/Gems/2.6.0/build_info
Using addressable 2.7.0
  /Library/Ruby/Gems/2.6.0/cache
Using atomos 0.1.3
  /Library/Ruby/Gems/2.6.0/doc

**Comment by maierj** [comment]
You can use the option `bundle-install-path` to specify a custom installation directory for Bundler:
https://github.com/maierj/fastlane-action#bundle-install-path
