### ISSUE TITLE
Potential monorepo issue: "Could not find fastlane in current directory."

### ISSUE THREAD

**Issue by jonathanstiansen** [maierj/fastlane-action#56]
Hello! Thank you for creating this action! I'm struggling a bit with understanding why I'm getting the following error:

```
[17:44:31]: Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?
```

This happens after installing gems, we have a monorepo - so we don't run fastlane in the root directory.

For the sake of simplicity, this is our directory structure:

```
root
  - customer
    - fastlane
    - ios
    - android
```

When using the actions argument: `subdirectory: customer` it says customer doesn't exist, instead I've opted to use the github action default for which directory to run in:

```
defaults:
  run:
    working-directory: customer
```

This installs the gems properly, but then when it goes to run I get the error displayed at the top. I assume it's because this action makes some assumptions about the shape directory? Is that what's happening? I'm also wondering if you've considered using the github action for caching the ruby gems?  [here](https://github.com/actions/cache/blob/main/examples.md#ruby---bundler) is where it's detailed.

**Comment by maierj** [comment]
Can you share your workflow definition? Do you have a checkout step before you run the fastlane action?

**Comment by M123-dev** [comment]
@jonathanstiansen I came across the same error. Did you managed to solve it?
