### ISSUE TITLE
Action download failure

### ISSUE THREAD

**Issue by ernestasgobionis** [maierj/fastlane-action#72]
Not sure if this is related to my job runner, or it's an issue with the action itself, but lately I have been getting this error when running a workflow that uses this action:

`
Warning: Failed to download action 'https://api.github.com/repos/maierj/fastlane-action/tarball/0eb8533f3529b655a335d7aa695b4d027fe5cc17'. Error: The operation was canceled.
Warning: Back off 23.441 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/maierj/fastlane-action/tarball/0eb8533f3529b655a335d7aa695b4d027fe5cc17'. Error: The operation was canceled.
Warning: Back off 16.671 seconds before retry.
Error: The operation was canceled.
`

Sometimes it seems to go through fine, but most of the time I'm getting this error.

First I was using `v1.4.0`, but still getting the same with `v2.0.1`

By the way, other actions are also being used in the same workflows, but they're downloaded without any errors

Any ideas on what might be going on here?

**Comment by spaskhalov** [comment]
Faced the same problem starting today. The following errors appear in the log:

`Download action repository 'maierj/fastlane-action@v2.0.1' (SHA:2121d31315dd0054a407c2c24938ae1fa29b883d)
Warning: Failed to download action 'https://api.github.com/repos/maierj/fastlane-action/tarball/2121d31315dd0054a407c2c24938ae1fa29b883d'. Error: The operation was canceled.
Warning: Back off 19.331 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/maierj/fastlane-action/tarball/2121d31315dd0054a407c2c24938ae1fa29b883d'. Error: The operation was canceled.
Warning: Back off 14.39 seconds before retry.`

I'm using `v2.0.1`

**Comment by ernestasgobionis** [comment]
In my case I noticed that restarting the workflow multiple times, sometimes it went through. Also noticed in the past few days that the error comes up less

**Comment by ernestasgobionis** [comment]
Problem seems to be gone, closing
