### ISSUE TITLE
Gemfile not being used despite being available in project's root

### ISSUE THREAD

**Issue by mazgajmaciek** [maierj/fastlane-action#79]
Looking at https://github.com/maierj/fastlane-action/blob/98ec59eaed5253a69f8dc414d61ae2390431be42/main.js#L50
fastlane-action is looking for Gemfile at project's root directory and if found, it should always execute fastlane action with `bundle exec`. However looking at the logs of my GH Actions CI run, fastlane is still saying `fastlane detected a Gemfile in the current directory. However, it seems like you didn't use bundle exec`

What am I doing wrong? My current GH workflow .yml file:

>     steps:
>       - name: app_center_test
>         uses: maierj/fastlane-action@v2.1.0
>         with:
>           lane: app_center_test
>           options: '{"conf": "dev"}'
>           bundle-install-path: 'vendor/bundle'
>           subdirectory: 'fastlane'

**Comment by maierj** [comment]
> Isn't the current directory changed at
> 
> https://github.com/maierj/fastlane-action/blob/98ec59eaed5253a69f8dc414d61ae2390431be42/main.js#L29
> 
> so it's not looking for `Gemfile` at root if `subdirectory` param is used in action's config?

Yes, that is intended behaviour. The `subdirectory` param is intended for repositories that contain multiple "projects" that each contain a `fastlane` folder, for example, if you have an iOS and Android project in the same repository and your folder structure looks like this
- /
  - iOS/
    - Gemfile
    - fastlane/
    - ...
  - Android
    - Gemfile
    - fastlane/
    - ...
   
If your fastlane folder is located at the root of you repository, which i suspect is the case for your repository, you don't need the `subdirectory` param.
