### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by danielehrhardt** [maierj/fastlane-action#87]
```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in [30] seconds.</h2>
<h2></h2>
</body></html>
```

**Comment by jgable** [comment]
I am also running into this error in my action logs. I think it's [this line](https://github.com/maierj/fastlane-action/blob/development/main.js#L19) doing something with action tracking.

**Comment by maierj** [comment]
Thanks for the feedback. There seems to be an issue with the usage tracking service. Until I can fix the service, I created a [new release](https://github.com/maierj/fastlane-action/releases/tag/v2.2.1) where usage tracking is disabled by default.

**Comment by akarabach** [comment]
same to me

**Comment by maierj** [comment]
Usage tracking will be removed in v3.0.0.
