### ISSUE TITLE
Bundler deployment mode

### ISSUE THREAD

**Issue by pstasiak** [maierj/fastlane-action#88]
I came across this point in the Bundler's documentation:
> Bundler's defaults are optimized for development. To switch to defaults optimized for deployment and for CI, use the --deployment flag

Shouldn't Bundler run with this option set on? Or, at least, there should be a flag for switching on / off the deployment mode. More info can be found here:
https://bundler.io/man/bundle-install.1.html#DEPLOYMENT-MODE

**Comment by maierj** [comment]
Starting from version 3.0.0, the `ruby/setup-ruby` action will be responsible for executing `bundle install`, so this issue is outside the scope of this action.
