### ISSUE TITLE
Node 12 is deprecated

### ISSUE THREAD

**Issue by fiserjCN** [maierj/fastlane-action#98]
Hello, I start to get following warning on our github action:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: maierj/fastlane-action

Hopefully it will be just about increasing the version in action.yml file, right? :)

**Comment by fiserjCN** [comment]
May be addressed by #91

**Comment by adam-leedy-mahana** [comment]
@fiserjCN were you able to find a solution to this? All of my actions appear to have died today because we are using this :(

**Comment by fiserjCN** [comment]
@adam-leedy-mahana Oh, sorry to hear that. This only emits a warning on my project so there was no need to look for a workaround yet.

**Comment by maierj** [comment]
I released a new version (https://github.com/maierj/fastlane-action/releases/tag/v2.3.0) with incremented Node version.
